---
- name: Install acme dependencies
  yum:
    name:
      - socat
      - wget

- name: Clone acme
  git:
    repo: https://github.com/acmesh-official/acme.sh.git
    dest: /opt/acme/src
    version: '{{ acme_version }}'

# https://github.com/acmesh-official/acme.sh/wiki/How-to-install#4-advanced-installation
- name: Install acme
  shell: |
    ./acme.sh --install \
      {{ "--nocron" if not acme_install_cronjob }} \
      {{ acme_install_options }}
  args:
    chdir: /opt/acme/src
    creates: /root/.acme.sh/acme.sh
    warn: false

- name: Configure DNS {{ acme_dns_api }}
  blockinfile:
    path: /root/.acme.sh/account.conf
    marker: "# {mark} {{ acme_dns_api }}"
    block: "{{ lookup('template', './templates/dns_' + acme_dns_api + '.conf.j2') }}"

- name: Issue certificate
  shell: |
    /root/.acme.sh/acme.sh \
      --issue \
      --dns dns_{{ acme_dns_api }} \
      -d {{ acme_domain }} \
      {{ '--staging' if acme_staging }}
  args:
    creates: /root/.acme.sh/{{ acme_domain }}/ca.cer
    warn: false
  register: acme__r_issue
  changed_when: "'skipped' not in acme__r_issue.stdout"

- name: Ensure directories are present for certificates
  file:
    path: '{{ item.path | dirname }}'
    state: directory
    mode: '{{ item.mode | default("0752") }}'
  loop:
    - path: '{{ acme_path_key }}'
      mode: '0700'
    - path: '{{ acme_path_cert }}'
    - path: '{{ acme_path_fullchain }}'
  when:
    - acme__r_issue.changed
    - item.path | default(None)

- name: Install certificate
  shell: |
    /root/.acme.sh/acme.sh \
      --install-cert -d {{ acme_domain }} \
      --key-file {{ acme_path_key }} \
      {{ "--cert-file " + acme_path_cert if acme_path_cert }} \
      {{ "--fullchain-file " + acme_path_fullchain if acme_path_fullchain }} \
      {{ "--reloadcmd " + acme_cmd_reload|quote if acme_cmd_reload }}
  args:
    warn: false
  register: acme__r_copy
  changed_when: "'Installing key to' in acme__r_copy.stdout"
  when:
    - acme__r_issue.changed
    - acme_path_key | default(None)
    - (acme_path_cert | default(None)) or (acme_path_fullchain | default(None))
